### PR TITLE
Aepp communications, bugfixing after merge, refactoring some components

### PR DESCRIPTION
**Pull request by petarbaykov**
- Fixing problem with updating balance in account, and problem with redirect to phishing warning when visiting scam page
Fixing issue #19 
- Injecting Aepp object 
- Aepp comunication
- Created Alert Component
- Sign popup validate balance
- Confirm or Reject close window
- Closing Sign popup resolve promise and return info
- Refactor Main Loader
- Refactor Loader
- ability to allow connection to wallet
- validate if login when open confirm popup and after login redirect to view
- ability to get balance of current active account
- Add responsiveness in sign transaction popup and allow connection popup
- validate input in aepp.request.connect method
- ability to remove all conected websites to wallet
- unifying postmessages responses

### CODE REVIEW

**Review by mradkov — COMMENTED** [review]
The `Aepp` object is correctly injected into the **chromium** based browsers the request for connection via `Aepp.request.connect()...` returns 

Screenshot 2019-07-11 at 17 01 18


```
{message: "Connection established"}
```
But when trying to request a signature for a transaction via

```
Aepp.request.sign({recipientId:"ak_2dY7HSsxH3yGL5j7mNvYYjFGTZwqtLNyoLSSaymn1wLKFSneeQ", amount: 0.01}).then(res => console.log(res))
```
The request is failing with the result:
```
{id: null, jsonrpc: "2.0", message: "Aepp not registered. Establish connection first"}
```

As for the firefox browser:
```Aepp.request.connect().then(res => console.log(res))```

shows the confirmation popup but clicking the confirm button does nothing and the result is:
```
Object { _c: [], _a: undefined, _s: 0, _d: false, _v: undefined, _h: 0, _n: false }
```

**Review by mradkov — COMMENTED** [review]
Can confirm the connection and tx signing request works now with chromium based browsers.

In firefox the issue is still present:

Screenshot 2019-07-11 at 17 18 58

**Comment by petarbaykov** [comment]
> The `Aepp` object is correctly injected into the **chromium** based browsers the request for connection via `Aepp.request.connect()...` returns
> 
> Screenshot 2019-07-11 at 17 01 18
> 
> ```
> {message: "Connection established"}
> ```
> 
> But when trying to request a signature for a transaction via
> 
> ```
> Aepp.request.sign({recipientId:"ak_2dY7HSsxH3yGL5j7mNvYYjFGTZwqtLNyoLSSaymn1wLKFSneeQ", amount: 0.01}).then(res => console.log(res))
> ```
> 
> The request is failing with the result:
> 
> ```
> {id: null, jsonrpc: "2.0", message: "Aepp not registered. Establish connection first"}
> ```
> 
> As for the firefox browser:
> `Aepp.request.connect().then(res => console.log(res))`
> 
> shows the confirmation popup but clicking the confirm button does nothing and the result is:
> 
> ```
> Object { _c: [], _a: undefined, _s: 0, _d: false, _v: undefined, _h: 0, _n: false }
> ```

Fixed in https://github.com/aeternity/aepp-waellet/pull/28

**Comment by petarbaykov** [comment]
> Can confirm the connection and tx signing request works now with chromium based browsers.
> 
> In firefox the issue is still present:
> 
> Screenshot 2019-07-11 at 17 18 58

Fixed in https://github.com/aeternity/aepp-waellet/pull/28

**Pull request merged**
