### PR TITLE
Send tx to named accounts, Switch token in Send page

### PR DESCRIPTION
**Pull request by petarbaykov**
- Fixing issue #45
- Fixing issue #44 - Now we can send tokens to account by both name and public_key
- List with all registered names for accounts
- Claimed names for accounts appears as name for account in all accounts list across the extension

### CODE REVIEW

**Comment by mradkov** [comment]
Registered AENS names are not visible listed in the settings page for some reason.

**Comment by petarbaykov** [comment]
> Registered AENS names are not visible listed in the settings page for some reason.

Is the name registered now or before

**Comment by mradkov** [comment]
> > Registered AENS names are not visible listed in the settings page for some reason.
> 
> Is the name registered now or before

Trying to register a name but it doesn't show up in the list below, also it is not showing already registered aens names from elsewhere.

I'm receiving the "success" popup tho.

**Comment by petbaik** [comment]
> tho

Can you tell me your public key

**Comment by petarbaykov** [comment]
> > > Registered AENS names are not visible listed in the settings page for some reason.
> > 
> > 
> > Is the name registered now or before
> 
> Trying to register a name but it doesn't show up in the list below, also registering it is not showing already registered aens names from elsewhere.
> 
> I'm receiving the "success" popup tho.

Can you tell me your public key

**Comment by petarbaykov** [comment]
> > > > Registered AENS names are not visible listed in the settings page for some reason.
> > > 
> > > 
> > > Is the name registered now or before
> > 
> > 
> > Trying to register a name but it doesn't show up in the list below, also registering it is not showing already registered aens names from elsewhere.
> > I'm receiving the "success" popup tho.
> 
> Can you tell me your public key

Or can you check what is the response from this request https://testnet.mdw.aepps.com/middleware/names/reverse/<your-public-key>

**Comment by mradkov** [comment]
> > > > Registered AENS names are not visible listed in the settings page for some reason.
> > > 
> > > 
> > > Is the name registered now or before
> > 
> > 
> > Trying to register a name but it doesn't show up in the list below, also registering it is not showing already registered aens names from elsewhere.
> > I'm receiving the "success" popup tho.
> 
> Can you tell me your public key

This is the one I'm trying with, which has `waellettest.test` name registered:
`ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X`

Update: Found out that this is registered on the mainnet (which I've tried from other service while tracking this error), rather than the testnet.
https://mdw.aepps.com/middleware/names/reverse/ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X

The testnet returns empty - so I assume the AENS registering is not working as expected.
https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X

**Comment by petarbaykov** [comment]
> > > > > Registered AENS names are not visible listed in the settings page for some reason.
> > > > 
> > > > 
> > > > Is the name registered now or before
> > > 
> > > 
> > > Trying to register a name but it doesn't show up in the list below, also registering it is not showing already registered aens names from elsewhere.
> > > I'm receiving the "success" popup tho.
> > 
> > 
> > Can you tell me your public key
> > This is the one I'm trying with, which has `waellettest.test` name registered:
> > `ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X`

I'm getting the registered names from this endpoint (https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X), but it seems that it doesn't return anything for your account 
image

**Comment by mradkov** [comment]
> > > > > > Registered AENS names are not visible listed in the settings page for some reason.
> > > > > 
> > > > > 
> > > > > Is the name registered now or before
> > > > 
> > > > 
> > > > Trying to register a name but it doesn't show up in the list below, also registering it is not showing already registered aens names from elsewhere.
> > > > I'm receiving the "success" popup tho.
> > > 
> > > 
> > > Can you tell me your public key
> > > This is the one I'm trying with, which has `waellettest.test` name registered:
> > > `ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X`
> 
> I'm getting the registered names from this endpoint (https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X), but it seems that it doesn't return anything for your account
> image

The issue is resolved. Problem was the middleware took few more minutes to cache the registered name.

Maybe we should think of faster way of doing this as its resulting to bad UX.

**Review by mradkov — APPROVED** [review]

**Pull request merged**
